StaffInfo/Models/Staff.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Staff_Extensions = new HashSet<Staff_Extensions>();
            this.BLOGs = new HashSet<BLOG>();
        }
    
        public int Staff_ID { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Gender { get; set; }
        public string Primary_Number { get; set; }
        public string Secondary_Number { get; set; }
        public string Email { get; set; }
        public string Temporary_Address { get; set; }
        public string Permanent_Address { get; set; }
        public string Qualification { get; set; }
        public string Job_Code { get; set; }
        public string Branch_Code { get; set; }
        public string Department_ID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Department Department { get; set; }
        public virtual Job_Title Job_Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_Extensions> Staff_Extensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOG> BLOGs { get; set; }
        public virtual User User { get; set; }
    }
}

StaffInfo/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StaffInfo.Models;
using System.Data.Entity;

namespace StaffInfo.Controllers
{
    public class StaffController : Controller
    {
        // GET: Staff
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetData()
        {
            using (DatabasModel db = new DatabasModel())
            {
                //var stafflist = db.STAFF_DETAILS().ToList();
                List<STAFF_DETAILS_Result> stafflist = db.STAFF_DETAILS().ToList();
                return Json(new { data = stafflist }, JsonRequestBehavior.AllowGet );
            }
        }

        [HttpGet]
        public ActionResult StaffRegister(int STAFF_ID= 0)
        {
            
            {
                using (DatabasModel db = new DatabasModel())
                {
                    List<SelectListItem> branchlist = new List<SelectListItem>();
                    List<SelectListItem> deptList = new List<SelectListItem>();
                    List<SelectListItem> joblist = new List<SelectListItem>();
                    foreach (Branch brh in db.Branches)
                    {
                        SelectListItem item = new SelectListItem()
                        {
                            Text = brh.Branch_Name,
                            Value = brh.Branch_Code.ToString(),
                            Selected = false
                        };
                        branchlist.Add(item);
                    }

                    foreach(Department dept in db.Departments)
                    {
                        SelectListItem item = new SelectListItem()
                        {
                            Text = dept.Department_Name,
                            Value = dept.Department_ID,
                            Selected = false
                        };
                        deptList.Add(item);
                    }

                    foreach(Job_Title jobTitle in db.Job_Title)
                    {
                        SelectListItem item = new SelectListItem()
                        {
                            Text = jobTitle.Position,
                            Value = jobTitle.Job_Title_Code,
                            Selected = false
                        };
                        joblist.Add(item);
                    }
                    ViewData["jobList"] = new SelectList(joblist.ToList(), "Value", "Text");
                    ViewData["branchList"] = new SelectList(branchlist.ToList(), "Value", "Text");
                    ViewData["deptList"] = new SelectList(deptList.ToList(), "Value", "Text");
                    //
                }
            }
            if (STAFF_ID != 0)
            {
                using(DatabasModel db = new DatabasModel())
                {
                    var mdl = db.Staffs.Where(x => x.Staff_ID == STAFF_ID).Select(x => new StaffModel
                    {
                        Staff_ID = x.Staff_ID,
                        First_Name = x.First_Name,
                        Middle_Name = x.Middle_Name,
                        Last_Name = x.Last_Name,
                        Gender = x.Gender,
                        Primary_Number = x.Primary_Number,
                        Secondary_Number = x.Secondary_Number,
                        Email = x.Email,
                        Temporary_Address = x.Temporary_Address,
                        Permanent_Address = x.Permanent_Address,
                        Qualification = x.Qualification,
                        Job_Code = x.Job_Code,
                        Branch_Code = x.Branch_Code,
                        Department_ID = x.Department_ID
                    }).ToList().FirstOrDefault();
                    return View(mdl);
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult AddExtension(int staffID)
        {
            using (DatabasModel db = new DatabasModel())
            {
                //var extNum = db.Staff_Extensions.Where(x => x.Staff_ID == staffID).Select(x => new StaffModel
                //{
                //    Extension_ID = x.Extension_ID,
                //    Staff_ID = x.Staff_ID,
                //    Extension_Num = x.Extension_Num,
                //    Extension_Num2 = x.Extension_Num2
                //}).FirstOrDefault();

                var extnNum = (from sx in db.Staff_Extensions join stf in db.Staffs 
                               on sx.Staff_ID equals stf.Staff_ID
                               select new { sx.Extension_ID, sx.Staff_ID, sx.Extension_Num, sx.Extension_Num2 }).Where(x => x.Staff_ID == staffID).Select(x => new StaffModel {
                                   Extension_ID = x.Extension_ID,
                                   Staff_ID = x.Staff_ID,
                                   Extension_Num = x.Extension_Num,
                                   Extension_Num2 = x.Extension_Num2
                               }).FirstOrDefault();

                try
                {
                    if (extnNum != null)
                    {
                        return View(extnNum);
                    }
                    else
                    {
                        var mdl = db.Staffs.Where(x => x.Staff_ID == staffID).Select(x => new StaffModel
                        {
                            Staff_ID = x.Staff_ID
                        }).FirstOrDefault();
                        return View(mdl);
                    }
                }
                catch(Exception ex)
                {
                    return Json(new { success = true, message = "Exception " + ex }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public ActionResult AddStaffExtension(Staff_Extensions stfExt)
        {
            using(DatabasModel db = new DatabasModel())
            {
                if (stfExt.Extension_ID == 0)
                {
                    db.Staff_Extensions.Add(stfExt);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Extension is added" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    db.Entry(stfExt).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated extension." }, JsonRequestBehavior.AllowGet);
                }
            }
        }


        [HttpPost]
        public ActionResult StaffRegister(Staff stf)
        {
            using (DatabasModel db = new DatabasModel())
            {
                if (stf.Staff_ID == 0)
                {
                    stf.Status = true;
                    db.Staffs.Add(stf);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Staff is registered.", JsonRequestBehavior.AllowGet });
                }
                else
                {
                    stf.Status = true;
                    db.Entry(stf).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated successfully" }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public ActionResult DeleteData(int staffID)
        {
            using(DatabasModel db = new DatabasModel())
            {
                var staf = db.Staffs.Where(x => x.Staff_ID == staffID).FirstOrDefault<Staff>();
                db.Entry(staf).Property(x => x.Status).CurrentValue = false;
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted successfully.", JsonRequestBehavior.AllowGet });
            }
        }

        [HttpPost]
        public JsonResult AutoCompleteJob(string jobName)
        {
            using(DatabasModel db = new DatabasModel())
            {
                var jobList = db.Job_Title.Where(x => x.Job_Title_Code.StartsWith(jobName)).Select(x => new
                {
                    Job_Title_Code = x.Job_Title_Code,
                    Position = x.Position
                }).ToList();
                return Json(new { data = jobList }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult AutoCompleteAddress(string addName)
        {
            using(DatabasModel db = new DatabasModel())
            {
                var addList = db.Addresses.Where(x => x.Address_Code.StartsWith(addName)).Select(x => new
                {
                    Address_Code = x.Address_Code,
                    Place_Name = x.Place_name
                }).ToList();
                return Json(new { data = addList }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AddExtension()
        {
            return View();
        }
    }
}

StaffInfo/Views/Staff/AddExtension.cshtml
@using StaffInfo.Models
@model StaffModel
    @{ 
        Layout = null;
    }
@Scripts.Render("~/Scripts/js")
@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/notify.min.js"></script>
@using (Html.BeginForm("AddStaffExtension", "Staff", FormMethod.Post, new { onsubmit = "return ExtensionAdd(this)", @class = "form-horizontal", role = "form" }))
{
    @Html.HiddenFor(model => model.Extension_ID)
    @Html.HiddenFor(model => model.Staff_ID)
    <div class="form-group form-control-sm">
        <div class="form-row">
            @Html.LabelFor(model => model.Extension_Num, "Extension Number", new { @class = "col-md-3" })

            @Html.TextBoxFor(model => model.Extension_Num, null, new { @class = "form-control col form-control-sm" })
            @Html.ValidationMessageFor(model => model.Extension_Num)
        </div>
    </div>
    <div class="form-group form-control-sm">
        <div class="form-row">
            @Html.LabelFor(model => model.Extension_Num2, "Extension Number 2", new { @class = "col-md-3" })

            @Html.TextBoxFor(model => model.Extension_Num2, null, new { @class = "form-control col form-control-sm" })
        </div>
    </div>
    <br />
    
    <text>If there is another extension you can fill up multiple.</text>
    <hr />
    <footer>
        <div class="form-group form-control-sm">
            <input type="reset" class="btn float-right btn-outline-dark" value="Reset" style="margin-left:5px" />
            <input type="submit" class="btn float-right btn-outline-dark" value="Register" />
        </div>
    </footer> 
}

StaffInfo/Views/Staff/Index.cshtml
@{ 
    @Html.Partial("_AdminNavBar")
}
@Scripts.Render("~/Scripts/js")
<h2>Staff Details</h2>   
<a class="btn btn-outline-dark btn-sm" style="margin-bottom:10px" onclick="StaffForm('@Url.Action("StaffRegister","Staff")')"><i class="fa fa-plus"></i> Add New</a>
<table id="staffTable" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Address</th>
            <th>Branch</th>
            <th>Department</th>
            <th>Degination</th>
            <th>Extension No.</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
</table>
@section scripts{
   
<script src="~/Scripts/Staff_JS/Admin_JS.js"></script>
    }

StaffInfo/Views/Staff/StaffRegister.cshtml
@using StaffInfo.Models
@model StaffModel
@{ 
    Layout = null;
}
@Scripts.Render("~/Scripts/js")
@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/notify.min.js"></script>
@using (Html.BeginForm("StaffRegister", "Staff", FormMethod.Post, new { onsubmit = "return StaffRegister(this)", @class = "form-horizontal", role = "form" }))
{
    <div class="container">

        @Html.HiddenFor(model => model.Staff_ID)
        <div class="form-row">
            <div class="form-group col-2 form-control-sm">
                @Html.Label("Full Name")
            </div>
            <div class="form-group col form-control-sm">
                @Html.TextBoxFor(model => model.First_Name, null, new { @class = "form-control form-control-sm", placeholder="First Name" })
                @Html.ValidationMessageFor(model => model.First_Name)
            </div>
            <div class="form-group col form-control-sm">
                @Html.TextBoxFor(model => model.Middle_Name, null, new { @class = "form-control form-control-sm", placeholder="Middle Name" })
            </div>
            <div class="form-group col form-control-sm">
                @Html.TextBoxFor(model => model.Last_Name, null, new { @class = "form-control form-control-sm", placeholder="Last Name" })
                @Html.ValidationMessageFor(model => model.Last_Name)
            </div>
        </div>
        <div class="form-group form-control-sm">
            <div class="form-row">
                <div class="col-md-2">
                    @Html.LabelFor(model => model.Gender)
                    @Html.ValidationMessageFor(model => model.Gender)
                </div>
                <div class="col form-check-inline">
                    @Html.RadioButtonFor(model => model.Gender, "Male", new { style = "margin-right:10px" })<text>Male </text>
                    @Html.RadioButtonFor(model => model.Gender, "Female", new { style = "margin-right:10px; margin-left:10px" })<text>Female</text>
                    @Html.RadioButtonFor(model => model.Gender, "Other", new { style = "margin-right:10px; margin-left:10px" })<text>Other</text>
                </div>
            </div>
            
        </div>
        <div class="form-group ">
            <div class="form-row">
                @Html.Label("Contacts", new { @class="col-2 form-control-sm", style = "margin-top:5px" })

                @Html.TextBoxFor(model => model.Primary_Number, null, new { @class = "form-control col form-control-sm", @placeholder = "Mobile", style = "margin-top:3px" })
                @Html.ValidationMessageFor(model => model.Primary_Number)

                @Html.TextBoxFor(model => model.Secondary_Number, null, new { @class = "form-control col form-control-sm", placeholder = "Phone", style = "margin-top:3px; margin-left:10px" })
            </div>
        </div>
        <div class="form-group">
            <div class="form-row">
                @Html.LabelFor(model => model.Email, "E-mail", new { @class = "col-2 col-form-label col-form-label-sm" })

                @Html.TextBoxFor(model => model.Email, null, new { @class = "form-control form-control-sm col", placeholder="abc@sunrisebank.com.np" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>
        <div class="form-group">
            <div class="form-row">
                @Html.Label("Address", new { @class = "col-2 form-control-sm", style = "margin-top:5px" })

                @Html.TextBoxFor(model => model.Temporary_Address, null, new { @class = "form-control col form-control-sm", @placeholder = "Temporary Address", style = "margin-top:3px" })
                @Html.ValidationMessageFor(model => model.Temporary_Address)

                @Html.TextBoxFor(model => model.Permanent_Address, null, new { @class = "form-control col form-control-sm", placeholder = "Permanent Address", style = "margin-top:3px; margin-left:10px" })
                @Html.ValidationMessageFor(model => model.Permanent_Address)
            </div>
        </div>
            <div class="form-group">
                <div class="form-row">
                    @Html.LabelFor(model => model.Qualification, "Qualification", new { @class="form-control-sm col-2"})
                    @Html.TextBoxFor(model => model.Qualification, null, new { @class = "form-control form-control-sm col", placeholder="Academic Certification" })
                    @Html.ValidationMessageFor(model => model.Qualification)
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4 form-control-sm">
                    @Html.LabelFor(model => model.Job_Code, "Job Title")
                    @Html.DropDownListFor(model => model.Job_Code, ViewData["jobList"] as SelectList, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(model => model.Job_Code)
                </div>
                <div class="form-group col-md-4 form-control-sm">
                    @Html.LabelFor(model => model.Branch_Code, "Branch Code")
                    @Html.DropDownListFor(model => model.Branch_Code, ViewData["branchlist"] as SelectList, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(model => model.Branch_Code)
                </div>
                <div class="form-group col-md-4 form-control-sm">
                    @Html.LabelFor(model => model.Department_ID, "Deparment ID")
                    @Html.DropDownListFor(model => model.Department_ID, ViewData["deptlist"] as SelectList, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(model => model.Department_ID)
                </div>
            </div>
       
        <footer>
            <br />
            <hr />
            <input type="reset" class="btn float-right btn-outline-dark btn-group-sm" value="Reset" style="margin-left:5px" />
            <input type="submit" class="btn float-right btn-outline-dark btn-group-ssssm" value="Submit" />
        </footer>
    </div>
}